config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("sample/", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("sslcommerz_social_django.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("", include("sslcommerz_social_django.students.urls", namespace="students")),
    path("sslcommerz/", include("sslcommerz_social_django.sslcommerz.urls", namespace="sslcommerz")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

sslcommerz_social_django/sslcommerz/urls.py
from django.urls import path
from .views import SSLCOMMERZ_GATEWAY, _sslcommerz_success, _sslcommerz_failed, _sslcommerz_cancel


app_name = "sslcommerz"
urlpatterns = [
    path("", SSLCOMMERZ_GATEWAY.as_view(), name="sslcommerz"),
    path("success/", _sslcommerz_success, name="sslcommerz-success"),
    path("fail/", _sslcommerz_failed, name="sslcommerz-fail"),
    path("cancel/", _sslcommerz_cancel, name="sslcommerz-cancel"),
]

sslcommerz_social_django/students/urls.py
from django.urls import path
from .views import Index, AddStudent, EditStudent, DeleteStudent


app_name = "students"
urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("add-student/", AddStudent.as_view(), name="add-student"),
    path("edit-student/<int:pk>/", EditStudent.as_view(), name="edit-student"),
    path("delete-student/<int:pk>/", DeleteStudent.as_view(), name="delete-student"),
]

sslcommerz_social_django/users/urls.py
from django.urls import path

from sslcommerz_social_django.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

sslcommerz_social_django/sslcommerz/models.py
from django.db import models

# Create your models here.

sslcommerz_social_django/students/models.py
from django.db import models

# Create your models here.


class Student(models.Model):
    student_number = models.PositiveIntegerField()
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    field_of_study = models.CharField(max_length=50)
    cgpa = models.FloatField()

    def __str__(self):
        return f'Student: {self.first_name} {self.last_name}'

sslcommerz_social_django/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for SSLCommerz Social Django.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

sslcommerz_social_django/students/forms.py
from django import forms
from .models import Student


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['student_number', 'first_name', 'last_name', 'email', 'field_of_study', 'cgpa']
        labels = {
            'student_number': 'Student Number',
            'first_name': 'First Name',
            'last_name': 'Last Name',
            'email': 'Email',
            'field_of_study': 'Field of Study',
            'cgpa': 'CGPA'
        }
        widgets = {
            'student_number': forms.NumberInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'field_of_study': forms.TextInput(attrs={'class': 'form-control'}),
            'cgpa': forms.NumberInput(attrs={'class': 'form-control'}),
        }

sslcommerz_social_django/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

sslcommerz_social_django/sslcommerz/views.py
from django.shortcuts import redirect, render
from django.views import View
from sslcommerz_lib import SSLCOMMERZ
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from uuid import uuid4
import pprint

# Create your views here.


class SSLCOMMERZ_GATEWAY(View):
    def get(self, request):
        sslcommerz_settings = {
            'store_id': settings.STORE_ID,
            'store_pass': settings.STORE_PASSWORD,
            'issandbox': True
        }
        sslcommerz = SSLCOMMERZ(sslcommerz_settings)
        post_body = {}
        post_body['total_amount'] = 10000
        post_body['currency'] = "BDT"
        post_body['tran_id'] = uuid4()
        post_body['success_url'] = "http://127.0.0.1:8000/sslcommerz/success/"
        post_body['fail_url'] = "http://127.0.0.1:8000/sslcommerz/fail/"
        post_body['cancel_url'] = "http://127.0.0.1:8000/sslcommerz/cancel/"
        post_body['emi_option'] = 0
        post_body['cus_name'] = "Customer Name"
        post_body['cus_email'] = "Customer Email"
        post_body['cus_phone'] = "Customer Phone"
        post_body['cus_add1'] = "Customer Address"
        post_body['cus_city'] = "Customer City"
        post_body['cus_country'] = "Customer Country"
        post_body['shipping_method'] = "NO"
        post_body['multi_card_name'] = ""
        post_body['num_of_item'] = 10
        post_body['product_name'] = "Product Name"
        post_body['product_category'] = "miscellaneous"
        post_body['product_profile'] = "miscellaneous"

        response = sslcommerz.createSession(post_body)
        pprint.pprint(response)

        return redirect(response["redirectGatewayURL"])

    def post(self, request):
        sslcommerz_settings = {
            'store_id': settings.STORE_ID,
            'store_pass': settings.STORE_PASSWORD,
            'issandbox': True
        }
        sslcommerz = SSLCOMMERZ(sslcommerz_settings)
        post_body = {}
        post_body['total_amount'] = 10000
        post_body['currency'] = "BDT"
        post_body['tran_id'] = uuid4()
        post_body['success_url'] = "http://127.0.0.1:8000/"
        post_body['fail_url'] = "http://127.0.0.1:8000/"
        post_body['cancel_url'] = "http://127.0.0.1:8000/"
        post_body['emi_option'] = 0
        post_body['cus_name'] = "Customer Name"
        post_body['cus_email'] = "Customer Email"
        post_body['cus_phone'] = "Customer Phone"
        post_body['cus_add1'] = "Customer Address"
        post_body['cus_city'] = "Customer City"
        post_body['cus_country'] = "Customer Country"
        post_body['shipping_method'] = "NO"
        post_body['multi_card_name'] = ""
        post_body['num_of_item'] = 10
        post_body['product_name'] = "Product Name"
        post_body['product_category'] = "miscellaneous"
        post_body['product_profile'] = "miscellaneous"

        response = sslcommerz.createSession(post_body)

        return redirect(response["redirectGatewayURL"])


class SSLCOMMERZ_PAYMENT_FAILED(View):
    @csrf_exempt
    def get(self, request):
        return redirect("students:index")


class SSLCOMMERZ_PAYMENT_CANCELLED(View):
    @csrf_exempt
    def get(self, request):
        return redirect("students:index")


class SSLCOMMERZ_PAYMENT_SUCCESS(View):
    @csrf_exempt
    def get(self, request):
        return redirect("students:index")


@csrf_exempt
def _sslcommerz_success(request):
    return redirect("students:index")


@csrf_exempt
def _sslcommerz_failed(request):
    return redirect("students:index")


@csrf_exempt
def _sslcommerz_cancel(request):
    return redirect("students:index")

sslcommerz_social_django/students/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from .models import Student
from .forms import StudentForm

# Create your views here.


class Index(View):
    def get(self, request):
        students = Student.objects.all()
        return render(request, 'students/index.html', {'students': students})


class AddStudent(View):
    def get(self, request):
        form = StudentForm()
        return render(request, 'students/add_student.html', {'form': form})

    def post(self, request):
        form = StudentForm(request.POST)
        if form.is_valid():
            form.save()
        return render(request, 'students/add_student.html', {'form': form, "success": True})


class EditStudent(View):
    def get(self, request, pk):
        student = Student.objects.get(id=pk)
        form = StudentForm(instance=student)
        return render(request, 'students/edit_student.html', {'form': form, 'student': student})

    def post(self, request, pk):
        student = Student.objects.get(id=pk)
        form = StudentForm(request.POST, instance=student)
        if form.is_valid():
            form.save()
        return render(request, 'students/edit_student.html', {'form': form, 'student': student, "success": True})


class DeleteStudent(View):
    def get(self, request, pk):
        student = Student.objects.get(id=pk)
        student.delete()
        return redirect('students:index')

sslcommerz_social_django/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

sslcommerz_social_django/templates/students/add_student.html
{% extends "base.html" %} {% block content %}
<h3 class="text-center m-4">Add Student</h3>
{% if success %}
<div class="alert alert-success" role="alert">
  The new student added successfully.
  <a href="{% url 'students:index' %}" class="alert-link">Go to Home Page.</a>
</div>
{% else %}
<div class="row justify-content-center">
  <div class="col-6">
    <div class="card bg-light mb-3">
      <div class="card-header">
        <i class="fa-solid fa-address-card fa-lg"></i> Student Registration
      </div>
      <div class="card-body">
        <form action="{% url 'students:add-student' %}" method="POST">
          {% csrf_token %} {{ form.as_p }}
          <button type="submit" class="btn btn-primary">Add</button>
          <a href="{% url 'students:index' %}" class="btn btn-secondary"
            >Cancel</a
          >
        </form>
      </div>
    </div>
  </div>
</div>
{% endif %} {% endblock %}

sslcommerz_social_django/templates/students/edit_student.html
{% extends "base.html" %} {% block content %}
<h3 class="text-center m-4">Update Student</h3>
{% if success %}
<div class="alert alert-success" role="alert">
  The student updated successfully.
  <a href="{% url 'students:index' %}" class="alert-link">Go to Home Page.</a>
</div>
{% else %}
<div class="row justify-content-center">
  <div class="col-6">
    <div class="card bg-light mb-3">
      <div class="card-header">
        <i class="fa-solid fa-pen-to-square fa-lg"></i> Update Student Records
      </div>
      <div class="card-body">
        <form
          action="{% url 'students:edit-student' student.id %}"
          method="POST"
        >
          {% csrf_token %} {{ form.as_p }}
          <button type="submit" class="btn btn-primary">Update</button>
          <a href="{% url 'students:index' %}" class="btn btn-secondary"
            >Cancel</a
          >
        </form>
      </div>
    </div>
  </div>
</div>
{% endif %} {% endblock %}

sslcommerz_social_django/templates/students/index.html
{% extends "base.html" %}
<!--  -->
{% block content %}
<!--  -->
<h1>Student Management System</h1>
<h3 class="m-4">All Students</h3>
<div class="row">
  <div class="col-12">
    {% if students %}
    <div class="card bg-light ms-4 me-4 mb-4">
      <div class="card-header">
        <i class="fa-solid fa-list fa-lg"></i> Student Records
      </div>
      <div class="card-body">
        <div class="card-text">
          <div class="table-responsive">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th scope="col">Student Number</th>
                  <th scope="col">First Name</th>
                  <th scope="col">Last Name</th>
                  <th scope="col">Email</th>
                  <th scope="col">Field of Study</th>
                  <th scope="col">CGPA</th>
                  <th scope="col">Actions</th>
                </tr>
              </thead>
              <tbody>
                {% for student in students %}
                <tr>
                  <td>{{ student.student_number }}</td>
                  <td>{{ student.first_name }}</td>
                  <td>{{ student.last_name }}</td>
                  <td>{{ student.email }}</td>
                  <td>{{ student.field_of_study }}</td>
                  <td>{{ student.cgpa }}</td>
                  <td>
                    <button
                      type="button"
                      class="btn btn-success me-1"
                      href="#"
                      data-bs-toggle="modal"
                      data-bs-target="#myModal{{student.id}}"
                    >
                      <i class="fa-solid fa-circle-info fa-lg"></i>
                    </button>

                    <!-- Modal - View Student -->
                    <div
                      class="modal"
                      id="myModal{{student.id}}"
                      tabindex="-1"
                      aria-labelledby="myModalLabel1"
                      aria-hidden="true"
                    >
                      <div class="modal-dialog" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title">
                              Student:
                              <!--  -->
                              {{ student.first_name }} {{ student.last_name }}
                            </h5>
                            <button
                              type="button"
                              class="btn-close"
                              data-bs-dismiss="modal"
                              aria-label="Close"
                            >
                              <span aria-hidden="true"></span>
                            </button>
                          </div>
                          <div class="modal-body">
                            <ul class="list-unstyled">
                              <li>
                                Student Number:
                                <strong>{{ student.student_number }}</strong>
                              </li>
                              <li>
                                First Name:
                                <strong>{{ student.first_name }}</strong>
                              </li>
                              <li>
                                Last Name:
                                <strong>{{ student.last_name }}</strong>
                              </li>
                              <li>
                                Email: <strong>{{ student.email }}</strong>
                              </li>
                              <li>
                                Field of Study:
                                <strong>{{ student.field_of_study }}</strong>
                              </li>
                              <li>CGPA: <strong>{{ student.cgpa }}</strong></li>
                            </ul>
                          </div>
                          <div class="modal-footer">
                            <a href="{% url 'sslcommerz:sslcommerz' %}">
                              <button type="button" class="btn btn-primary">
                                Pay Now
                              </button>
                            </a>
                            <button
                              type="button"
                              class="btn btn-primary"
                              data-bs-dismiss="modal"
                            >
                              Close
                            </button>
                          </div>
                        </div>
                      </div>
                    </div>
                    <a
                      class="btn btn-warning me-1"
                      href="{% url 'students:edit-student' student.id %}"
                    >
                      <i class="fa-solid fa-pen-to-square fa-lg"></i>
                    </a>

                    <button
                      type="button"
                      class="btn btn-danger"
                      data-bs-toggle="modal"
                      data-bs-target="#delete{{student.id}}"
                    >
                      <i class="fa-solid fa-trash-can fa-lg"></i>
                    </button>

                    <!-- Modal - Delete Student -->
                    <div
                      class="modal"
                      id="delete{{student.id}}"
                      tabindex="-1"
                      aria-labelledby="myModalLabel2"
                      aria-hidden="true"
                    >
                      <div class="modal-dialog" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title">
                              Student:
                              <!--  -->
                              {{ student.first_name }} {{ student.first_name }}
                            </h5>
                            <button
                              type="button"
                              class="btn-close"
                              data-bs-dismiss="modal"
                              aria-label="Close"
                            >
                              <span aria-hidden="true"></span>
                            </button>
                          </div>
                          <div class="modal-body">
                            <p>Are you sure you want to delete this student?</p>
                          </div>
                          <div class="modal-footer">
                            <a
                              href="{% url 'students:delete-student' student.id %}"
                            >
                              <button
                                type="button"
                                class="btn btn-primary"
                                data-bs-dismiss="modal"
                              >
                                Delete
                              </button></a
                            >
                            <button
                              type="button"
                              class="btn btn-secondary"
                              data-bs-dismiss="modal"
                            >
                              Cancel
                            </button>
                          </div>
                        </div>
                      </div>
                    </div>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    {% else %}
    <h5 class="alert alert-primary ms-4 me-4">No Student Records</h5>
    {% endif %}
  </div>
</div>
{% endblock %}